### ISSUE TITLE
How to use my own dataset to run this code?

### ISSUE THREAD

**Issue by MoyangSensei** [franciszchen/SWD-Net#2]
After I read your article, I was greatly inspired. I am also doing super-resolution research on pathological images of breast cancer sections.
Can you expose the code and process of making datasets? I need to use it to make my own dataset to get results in your model.
At the same time, I also hope to get in touch with you. Here are my two emails:
jfy539@yeah.net
1246487376@qq.com
Thank you！

**Comment by MoyangSensei** [comment]
I am looking forward to your reply:)

**Comment by franciszchen** [comment]
Thanks for your interest! The code for the preparation of lmdb dataset has been uploaded to the ./mk_lmdb folder. In fact, the preparation of lmdb format is a little cumbersome. I would recommend using original image pairs or npy format with corresponding dataset script to use this project for new datasets.
